name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: flutter-pop-up-app-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
        
    - name: Create Release (on main branch push)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          ## Flutter Pop-up App APK
          
          This release contains the APK file for the Flutter Pop-up App.
          
          ### Features:
          - Random pop-up sequence on app startup
          - 4 different pop-up types with proper randomization
          - Modal pop-ups that must be handled
          - App closing functionality
          - Welcome screen choice system
          
          ### Installation:
          1. Download the APK file below
          2. Enable "Install from unknown sources" on your Android device
          3. Install the APK file
          
          ### Test Automation Challenge:
          This app is designed for test automation challenges with random pop-up sequences.
        files: build/app/outputs/flutter-apk/app-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
